### ISSUE TITLE
Handle fallback when no "property" attribute

### ISSUE THREAD

**Issue by thomasbertet** [johnreutersward/opengraph#3]
Hi there, 

We found out some websites are not using OG correctly.
There are some cases were they do not use the "property" attribute to specify the og attribute name.
ie:
`<meta name="og:type" content="website">`
Here it uses the "name" attribute instead of "property".

You can check it there for example : www.hermes.com/applewatchhermes/fr/

We had to patch your nice library to handle this case unfortunately, and I was wondering if you would consider adding this patch to your lib ? If so, I can surely create a PR. That said, I won't blame you to not support incorrect use of the OG protocol ;)

Regards, and thanks for this nice tiny lib !

**Comment by johnreutersward** [comment]
Hi Thomas, 

Thanks for brining this up, I had not seen this before.
It makes sense that some site would use "name" given that the meta tag has no "property" attribute in the spec.

I think a fallback approach would work well, please submit a PR.

Thanks

**Comment by johnreutersward** [comment]
Fixed in https://github.com/rojters/opengraph/commit/963e8b3e25812abf6df13bf108fef2c3dc1c90e3
